[theme]
base = "dark"
primaryColor = "#2dd4bf"
backgroundColor = "#080c15"
secondaryBackgroundColor = "#0d1422"
textColor = "#dce5f0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
